"""add_dashboard_users

Revision ID: b436f6e8a91b
Revises: 12f7e9ab8c9f
Create Date: 2026-05-20 13:41:28.502312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b436f6e8a91b'
down_revision: Union[str, Sequence[str], None] = '12f7e9ab8c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_users_username'), ['username'], unique=True)

    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('caller_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_column('caller_name')
        batch_op.drop_column('status')

    with op.batch_alter_table('dashboard_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_users_username'))

    op.drop_table('dashboard_users')
    # ### end Alembic commands ###
